modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
# issueTrackerURL="https://github.com/LordGrimmauld/discordchat/issues"

[[mods]]
modId="armhead"
version="1.0"
displayName="Arm Hat"
#updateJSONURL=""
authors="Grimmauld"
description='''
Put mechanical arms on your head'''

[[dependencies.armhead]]
modId="forge"
mandatory=true
versionRange="[36.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.armhead]]
modId="minecraft"
mandatory=true
versionRange="[1.16.3,1.17)"
ordering="NONE"
side="BOTH"